name: Update Currency Rates

on:
  schedule:
    - cron: '0 23 * * 1-5'  # À 23H00 du lundi au vendredi
  workflow_dispatch:        # Permet aussi de lancer manuellement

permissions:
  contents: write
  deployments: write

jobs:
  update:
    if: github.repository_owner == 'aurelien-f'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'  # Mise à jour vers la dernière version
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Run update script
        run: node scripts/cron_donwload_cvs.js
        
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          git commit -m "🤖 MAJ automatique des taux de change" || exit 0
          git push
        
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          vercel build --prod --token=$VERCEL_TOKEN
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN 
